steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/slh-rag/gae-flexible/api-service:latest",
        "-f",
        "Dockerfile.api",
        ".",
      ]
images:
  - "us-central1-docker.pkg.dev/slh-rag/gae-flexible/api-service:latest"
